-- SQL Script to update 'about_quiz' column with rich SEO descriptions for all quizzes (3 Paragraphs per quiz)
-- Database: u691843472_quiztv2 / QuizTv

START TRANSACTION;

-- First, ensure the 'about_quiz' column exists in 'quizzes' table
SET @exist := (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'quizzes' AND column_name = 'about_quiz');
SET @sql := IF(@exist = 0, 'ALTER TABLE `quizzes` ADD COLUMN `about_quiz` TEXT NULL AFTER `description`', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- Update Quiz ID 1: Medical Terminology Test
UPDATE `quizzes` SET `about_quiz` = 'Medical terminology can feel like a foreign language to anyone outside the healthcare field. From complex hospital shorthand and prescription abbreviations to clinical jargon for symptoms, surgical procedures, and anatomical structures, healthcare professionals rely on a precise, standardized vocabulary to communicate critical patient information quickly and accurately under high-pressure conditions.\n\nThis comprehensive medical terminology test evaluates your ability to decode clinical language, prescription drug labels, vital sign monitoring terms, and diagnostic codes. Throughout the quiz, you will encounter real-world healthcare scenarios involving cardiovascular terms, emergency care protocols, body system classifications, and medical suffixes that govern daily hospital communication.\n\nWhether you are currently studying nursing or pre-med, work in healthcare administration, or simply want to benchmark your personal medical literacy, this staged test will challenge your knowledge. Take the quiz to see if your clinical vocabulary is sharp enough to score in the top 20%!' WHERE `id` = 1;

-- Update Quiz ID 2: Medicine Entrance Exam
UPDATE `quizzes` SET `about_quiz` = 'Medical entrance exams test far more than basic biological facts—they evaluate diagnostic speed, critical reasoning, patient chart interpretation, and calm decision-making under intense pressure. Designed to simulate the mental rigor of competitive medical school evaluations, this challenge presents clinical case hints, anatomical memory callbacks, and rapid triage choices.\n\nIn a clinical environment, doctors must process subtle symptoms, analyze laboratory values, and synthesize medical history in seconds. This exam tests your capacity to identify underlying conditions, avoid common diagnostic traps, and prioritize life-saving interventions while keeping a steady head under timed constraints.\n\nOnly a small fraction of candidates manage to pass this rigorous medicine entrance check on their first attempt. Step into the shoes of a medical student, test your problem-solving reflexes, and discover if you have the analytical sharpness required for a career in medicine.' WHERE `id` = 2;

-- Update Quiz ID 3: Navy Entrance Test
UPDATE `quizzes` SET `about_quiz` = 'Serving in the Navy demands exceptional situational awareness, fast mathematical reasoning, maritime chart reading, and flawless team communication under challenging oceanic environments. Naval entrance evaluations assess candidate aptitude across seamanship fundamentals, vessel navigation rules, flag and light signaling, mechanical comprehension, and tactical sea control.\n\nOn the deck of a modern naval vessel or within the nerve center of a ship\'s bridge, officers and crew members must read weather patterns, interpret radar signals, execute emergency damage control, and maintain operational discipline. This test brings together real-world naval mission challenges to evaluate your leadership instincts and technical knowledge.\n\nWhether you are fascinated by naval history, considering a military career, or want to challenge your crisis management skills, this quiz puts your naval readiness to the test. Step up to the bridge, navigate complex harbor maneuvers, and prove your command capabilities!' WHERE `id` = 3;

-- Update Quiz ID 4: Air Force Test
UPDATE `quizzes` SET `about_quiz` = 'Military aviation demands split-second reaction times, acute spatial orientation, cockpit instrument reading, and laser-focused concentration under rapid altitude and speed changes. The Air Force flight candidate and officer evaluations assess your grasp of aerodynamics, air traffic control vectors, navigation instruments, and flight safety protocols.\n\nInside a high-performance cockpit or tactical flight control center, pilots must constantly monitor airspeed, altimeters, fuel metrics, and radar vectors while executing complex flight paths. This aviation challenge tests your ability to interpret flight instruments, calculate intercept trajectories, and make sound tactical calls under simulated pressure.\n\nDesigned to mirror flight simulator evaluation standards and aerial mission logic, this test challenges your reflexes and spatial intelligence. Climb into the cockpit, take control of the flight instruments, and see if you have the sharpness required to earn your Air Force wings!' WHERE `id` = 4;

-- Update Quiz ID 5: Karmic, Soulmate, Or Twin Flame Connection
UPDATE `quizzes` SET `about_quiz` = 'Have you ever met someone and experienced an immediate, inexplicable sense of familiarity, intense magnetic pull, or deep emotional recognition? Throughout history, relationship experts and spiritual traditions have categorized profound human bonds into three distinct profiles: Karmic connections, Soulmate relationships, and Twin Flame partnerships.\n\nKarmic relationships are passionate and intense, designed to teach essential personal growth lessons and break old emotional patterns. Soulmate relationships offer deep harmony, natural alignment, and enduring emotional comfort. Twin Flame connections act as intense spiritual mirrors, reflecting your deepest strengths, vulnerabilities, and spiritual potential.\n\nBy answering questions about your emotional chemistry, communication dynamics, intuition, and shared life values, this personality quiz reveals the true nature of your bond profile. Explore your connection dynamics and gain meaningful insight into your relationship journey.' WHERE `id` = 5;

-- Update Quiz ID 6: Memory Test
UPDATE `quizzes` SET `about_quiz` = 'Working memory and visual recall are vital cognitive functions that govern how effectively our brains process, store, and retrieve daily information. From remembering multi-digit numerical sequences and subtle visual details to recalling delayed clues across multiple stages, a strong memory enhances daily focus, learning speed, and problem-solving efficiency.\n\nThis staged memory challenge features 10 progressive rounds designed to test different facets of your cognitive recall. You will encounter quick fact capture, visual pattern matching, delayed sequence memory, category recall, and mixed detail retention that progressively challenge your short-term and long-term memory capacity.\n\nRegularly testing and exercising your memory helps maintain cognitive sharpness and visual acuity. Challenge your brain, track how many visual details you can remember across 10 rounds, and see how your memory performance compares to global averages!' WHERE `id` = 6;

-- Update Quiz ID 7: IQ Challenge
UPDATE `quizzes` SET `about_quiz` = 'Spatial reasoning, abstract logic, numerical pattern detection, and fluid intelligence form the foundation of standardized cognitive evaluation frameworks. This comprehensive 11-stage IQ challenge is engineered to test your mental agility, pattern completion, matrix reasoning, and visual deduction under timed conditions.\n\nCognitive problem-solving involves identifying subtle rules hidden within complex geometric grids, mental transformations, numeric progressions, and logical sequences. As you advance through each stage, the questions demand higher levels of concentration, visual-spatial manipulation, and rule-switching capability.\n\nWhether you love tackling complex logic puzzles or want to benchmark your analytical intelligence against thousands of players worldwide, this challenge provides a thorough mental workout. Sharpen your analytical focus and discover how high your logical reasoning can score!' WHERE `id` = 7;

-- Update Quiz ID 8: Garage Tools Quiz
UPDATE `quizzes` SET `about_quiz` = 'Every experienced auto mechanic, craftsman, and DIY enthusiast knows that selecting the right tool for the job is essential for safety, precision, and efficiency. From fundamental hand tools like torque wrenches, ratchets, and micrometers to heavy-duty workshop machinery, pneumatic tools, and diagnostic scanners, garage tools form the heart of modern maintenance.\n\nThis visual photo-identification quiz tests your technical literacy across basic and advanced workshop gear. You will encounter questions covering gripping and cutting tools, precision measurement instruments, specialty repair equipment, hydraulic jacks, and workshop safety essentials used in professional automotive garages.\n\nWhether you spend weekends working on cars in your garage, work in trades, or simply want to test your practical knowledge, this tool identification quiz will put your expertise to the test. Can you name these essential workshop tools like a master mechanic?' WHERE `id` = 8;

-- Update Quiz ID 9: Vision Test
UPDATE `quizzes` SET `about_quiz` = 'Color vision acuity, visual contrast sensitivity, and pattern recognition enable our eyes and optical processing centers to interpret complex visual surroundings. Inspired by standardized Ishihara color plates and visual perception tests, this staged visual challenge evaluates your ability to spot hidden numbers, geometric shapes, and low-contrast symbols.\n\nThroughout 10 progressive rounds, you will analyze vibrant color spectrums, subtle hue variations, overlapping letters, and low-contrast pattern plates. The test measures how effectively your visual system distinguishes subtle chromatic differences and extracts fine background details under varying visual environments.\n\nTaking regular visual perception challenges is a great way to test your eye for detail and visual focus. Step through the progressive color plates, challenge your visual discrimination skills, and see how sharp your color perception really is!' WHERE `id` = 9;

-- Update Quiz ID 10: True Zodiac Sign Quiz
UPDATE `quizzes` SET `about_quiz` = 'While your birth date determines your traditional astrological sun sign, your personality traits, decision-making style, emotional responses, and social energy often align with a completely different zodiac profile. Astrological symbolism groups signs into four primary element energies: Fire (bold and passionate), Earth (grounded and practical), Air (intellectual and communicative), and Water (intuitive and empathetic).\n\nThis reflective personality quiz goes beyond birth dates to examine how you think, communicate, handle challenges, and form personal connections. By evaluating your core values, intuition, social drive, and creative instincts, the quiz identifies the zodiac sign that mirrors your true behavioral essence.\n\nAre you a visionary Aquarius, an ambitious Capricorn, a passionate Leo, or an intuitive Cancer? Answer these engaging personality questions to uncover your true energetic zodiac sign!' WHERE `id` = 10;

-- Update Quiz ID 11: Everyday Grammar Challenge
UPDATE `quizzes` SET `about_quiz` = 'Clear, effective communication relies on accurate grammar, proper punctuation, correct subject-verb agreement, and precise word selection. Common writing mistakes—such as dangling modifiers, pronoun ambiguity, misplaced commas, and homophone confusion—can alter sentence meaning and diminish professional credibility.\n\nThis practical grammar challenge guides you through 10 structured rounds focused on everyday writing scenarios, sentence structure analysis, word choice refinement, and editorial proofreading. You will test your ability to spot subtle syntax errors, choose correct prepositions, and polish complex sentences.\n\nWhether you are writing professional emails, academic essays, or creative content, mastering grammar enhances your written expression. Challenge your editorial skills and see if your grammar knowledge meets expert standards!' WHERE `id` = 11;

-- Update Quiz ID 12: World History Challenge
UPDATE `quizzes` SET `about_quiz` = 'From ancient river valley civilizations and monumental wonders to groundbreaking scientific discoveries, global trade routes, and historic treaties, world history is a rich narrative of human ambition and societal evolution. Understanding historical events provides valuable context for the geopolitical and cultural landscapes of our modern world.\n\nThis staged historical knowledge quiz spans key epochs across ancient empires, medieval trade networks, the Renaissance, the Industrial Revolution, and modern global milestones. You will encounter questions about influential leaders, iconic architecture, historical timelines, and major civilizational turning points.\n\nWhether you are a history buff, student, or curious lifelong learner, this quiz offers an engaging voyage through time. Test your historical memory and see how well you know the monumental events that built human civilization!' WHERE `id` = 12;

-- Update Quiz ID 13: Can You Catch the Trick?
UPDATE `quizzes` SET `about_quiz` = 'Some questions seem deceptively simple when you first read them—until you realize they are cleverly crafted to lead your mind toward an obvious, but incorrect, assumption! Trick questions and lateral thinking puzzles test your ability to read phrasing carefully, challenge initial impressions, and think outside traditional boundaries.\n\nThis brain-twisting quiz focuses on wordplay tricks, visual illusions, counter-intuitive scenarios, double meanings, and subtle logical paradoxes. To succeed, you must slow down, analyze every word in the prompt, and question what the question is really asking.\n\nLateral thinking exercises improve cognitive flexibility and help you approach real-world problem solving with a fresh perspective. Take the quiz, stay sharp, and discover how many trick questions you can solve without falling into the trap!' WHERE `id` = 13;

-- Update Quiz ID 16: General Knowledge Challenge
UPDATE `quizzes` SET `about_quiz` = 'General knowledge encompasses a broad range of topics including world geography, physical sciences, historical milestones, literature, arts, and popular culture. Cultivating a diverse knowledge base improves cognitive adaptability, memory retrieval speed, and everyday conversational intelligence.\n\nThis engaging trivia challenge tests your familiarity with diverse facts from around the globe. You will encounter questions covering scientific discoveries, global capitals, famous literary works, historical figures, and general world trivia that challenge your memory.\n\nExpanding your general knowledge is both fun and mentally stimulating. Take this quiz to challenge your intellect, discover intriguing new facts, and see how well-rounded your general knowledge truly is!' WHERE `id` = 16;

-- Update Quiz ID 18: Elementary Geography Quiz
UPDATE `quizzes` SET `about_quiz` = 'Geography connects us to the extraordinary landscapes, cultural regions, world capitals, continents, oceans, and natural landmarks of our planet. Studying physical and human geography builds global awareness and helps us appreciate the natural forces that shape Earth\'s climate zones, landforms, and ecosystems.\n\nFeaturing questions on iconic physical landmarks, world capital cities, major mountain ranges, ocean currents, and country boundaries, this elementary geography quiz offers an educational overview of world geography. It is designed for students, families, and trivia enthusiasts of all ages.\n\nExplore world maps, test your knowledge of global locations, and discover fascinating geographic facts. Take the quiz today to see how well you know our world!' WHERE `id` = 18;

-- Update Quiz ID 19: Life Before The Internet
UPDATE `quizzes` SET `about_quiz` = 'Before Wi-Fi networks, instant search engines, streaming media, and smartphones, everyday life operated at a completely different rhythm. People navigated road trips using paper highway maps, researched school projects using multi-volume encyclopedia sets, rented VHS movies at local video stores, and waited days for camera film to be developed.\n\nCommunication relied on landline telephones, handwritten letters, and face-to-face conversations. Entertainment meant recording radio songs onto cassette mixtapes, browsing print catalogs, reading morning newspapers, and gathering around television sets for scheduled broadcasts.\n\nThis nostalgic trivia quiz takes you on a fun trip back through pre-digital lifestyle habits, retro technology, vintage media formats, and analog culture. Step back in time, rekindle fond memories, and test how well you remember life before the internet connected the world!' WHERE `id` = 19;

-- Update Quiz ID 20: Legendary Cars Quiz
UPDATE `quizzes` SET `about_quiz` = 'Automotive history is rich with legendary vehicles that defined eras, pioneered engineering breakthroughs, and captured the imagination of car enthusiasts worldwide. From classic American muscle cars and sleek European sports cars to rally icons, grand tourers, and timeless luxury automobiles, iconic cars represent the perfect marriage of design artistry and mechanical performance.\n\nThis automotive history challenge tests your knowledge of famous car models, engine innovations, historic racing triumphs, and legendary body designs. You will encounter questions covering classic V8 muscle, high-performance European engineering, iconic motorsport victories, and groundbreaking automotive designs.\n\nWhether you are a lifelong gearhead, classic car collector, or motorsport fan, this quiz will put your automotive knowledge to the test. Challenge yourself and see if you can identify these legendary automobiles!' WHERE `id` = 20;

-- Update Quiz ID 21: Biology Quiz Challenge
UPDATE `quizzes` SET `about_quiz` = 'Biology is the captivating science of life, exploring everything from microscopic cellular structures and genetic DNA code to plant photosynthesis, human organ systems, and complex ecological webs. Understanding biological principles helps us appreciate how living organisms survive, adapt, and interact within delicate environments.\n\nThis introductory biology quiz covers foundational concepts in cell biology, human anatomy, genetics, circulatory systems, plant biology, and animal behavior. Throughout the quiz, you will test your grasp of essential biological processes that sustain life on Earth.\n\nWhether you are studying high school or college biology, preparing for science exams, or simply curious about the natural world, this quiz provides a rewarding educational challenge. Test your biology knowledge and explore the science of life!' WHERE `id` = 21;

COMMIT;
